name: build-$(Build.BuildId)-date-$(Date:yyyy-MM-dd)
jobs:
  - job: PowerShellPesterJob
    displayName: PowerShell Pester Test Runner
    pool: Hosted VS2017
    steps:
    - powershell: ./'$(Build.SourcesDirectory)/scripts/run-pester.ps1'
      arguments: '-Verbose'
      displayName: 'Invoke-Pester'
      errorActionPreference: stop
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        testResultsFiles: $(Common.TestResultsDirectory)\TEST-pester-$(Build.BuildNumber).xml
        testResultFormat: NUnit
