name: build-$(Build.BuildId)-date-$(Date:yyyy-MM-dd)
jobs:
  - job: PowerShellPesterJob
    displayName: PowerShell Pester Test Runner
    steps:
    - task: PowerShell@2
      displayName: 'Invoke-Pester'
      inputs:
        targetType: filePath
        filePath: '$(Build.SourcesDirectory)/scripts/run-pester.ps1'
        arguments: '-Verbose'
        errorActionPreference: stop
      continueOnError: true
    - task: PublishTestResults@2
      displayName: Publish Test Results
      inputs:
        searchFolder: $(Common.TestResultsDirectory)
        testResultsFiles: TEST-pester-$(Build.BuildNumber).xml
        testResultFormat: NUnit
