name: $(Date:yyyy-MM-dd)-rev$(Rev:r)
trigger:
  batch: true
  branches:
    include:
    - master
    - rel/*
pr:
- '*'
resources:
  repositories:
  - repository: templates
    type:       github
    name:       thnetii/azure-pipelines
    endpoint:   couven92
jobs:
- job: PowerShellPesterJob
  displayName: PowerShell Pester Test Runner
  steps:
  - pwsh: $(Build.SourcesDirectory)/scripts/run-pester.ps1
    displayName: Invoke-Pester
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      searchFolder: $(Common.TestResultsDirectory)
      testRunTitle: $(Build.BuildNumber)
      testResultsFiles: '**/TEST-*.xml'
      testResultsFormat: NUnit
      buildPlatform: $(Agent.OS)-$(Agent.OSArchitecture)
      buildConfiguration: $(Build.DefinitionName)
- template: templates/dotnetcore/azure-pipelines.yml@templates
  parameters:
    checkout:
    - checkout:   self
      submodules: true
    presteps:
    - task: UseDotNet@2
      displayName:  Use .NET Core SDK version 3.x
      inputs:
        version:    3.x
